### ISSUE TITLE
Submodules can't be found on GitHub

### ISSUE THREAD

**Issue by kartaris** [dimkanovikov/starc#28]
Next repositories can't be found on GitHub. Are they private?

https://github.com/dimkanovikov/starc-location-information-plugin.git
https://github.com/dimkanovikov/starc-character-information-plugin.git
https://github.com/dimkanovikov/starcloud

**Comment by dimkanovikov** [comment]
Yes, they are private.

**Comment by kartaris** [comment]
Okay. I tried to build application on MacOS and found that they are not needed to build it.
Application still can't start on MacOS but because of it can't find coreplugin in application bundle. 
I will open new issue and close this one.

**Comment by dimkanovikov** [comment]
Yup, there is an issue with plugins locations for the developer build. Check out [this](https://github.com/dimkanovikov/starc/blob/master/src/app/main.cpp#L32) and [this](https://github.com/dimkanovikov/starc/blob/master/src/core/management_layer/content/project/project_plugins_builder.cpp#L114) :)

**Comment by dimkanovikov** [comment]
Okay, issue with building app for Mac fixed now.
