### ISSUE TITLE
linux x11 bugs with icons 

### ISSUE THREAD

**Issue by NursultanDev** [dimkanovikov/starc#29]
## no ui icons, just squares instead 
what is the reason for this?

![изображение](https://user-images.githubusercontent.com/77955381/114021103-2054af00-9892-11eb-9fbf-3c893c617450.png)

**Comment by dimkanovikov** [comment]
Any debug messages in the Qt Creator's Application Output panel?

**Comment by NursultanDev** [comment]
![изображение](https://user-images.githubusercontent.com/77955381/114033014-b68ed200-989e-11eb-97fb-450247e5e7b3.png)
just this

**Comment by dimkanovikov** [comment]
Вкладка «вывод приложения»

**Comment by NursultanDev** [comment]
там нечего не написано но во вкладке "Основные сообщения" вывело вот это

> Project MESSAGE: This project is using private headers and will therefore be tied to this specific Qt module build version.
Project MESSAGE: Running this project against other versions of the Qt modules may crash at any arbitrary point.
Project MESSAGE: This is not a bug, but a result of using Qt internals. You have been warned!

**Comment by NursultanDev** [comment]
на какой версии Qt вы собираете?

**Comment by dimkanovikov** [comment]
Да на разных собираю, это не зависит от версии. По всей видимости не подтянулся файл с ресурсами, нужно смотреть в эту сторону.

**Comment by NursultanDev** [comment]
хорошо посмотрю

**Comment by dimkanovikov** [comment]
Иконки находятся в шрифте, который лежит в resources.qrc
